Repository WildCodeSchool/0322_P3_Php_Lyon_Irep, pull requests merged in 2023-07, with the labels that each got.

#46 S 06 optimisation twitter
  assets/modal.js
  src/Controller/AdminController.php
  src/Controller/TwitterController.php
  src/DataFixtures/ExhibitionFixtures.php
  src/DataFixtures/PageVisitFixtures.php
  src/DataFixtures/PictureFixtures.php
  templates/admin/index.html.twig
  templates/includes/_navbar.html.twig
  templates/includes/_sidebar.html.twig
  templates/includes/footer.html.twig
  templates/picture/show.html.twig
  templates/security/login.html.twig
  templates/twitter/preview.html.twig
Labels: Changes done

#47 Download exhibition catalogue by admin
  .gitignore
  assets/cropper.js
  assets/styles/cropper.scss
  src/Controller/GeneratePdfController.php
  src/Controller/PictureController.php
  src/Service/CroppedService.php
  src/Service/GeneratePdfService.php
  templates/picture/index.html.twig
  templates/picture/show.html.twig
Labels: Changes done

#48 S 06 add gallery for exhibition
  assets/controllers/hello_controller.js
  assets/formPicture.js
  assets/statistic.js
  src/Controller/AdminController.php
  src/Controller/ExhibitionController.php
  src/Controller/PictureController.php
  src/Entity/Picture.php
  src/Form/PictureType.php
  src/Service/CategoryService.php
  src/Service/StatisticService.php
  templates/admin/presentation/index.html.twig
  templates/admin/statistics.html.twig
  templates/picture/_delete_form.html.twig
  templates/picture/_form.html.twig
  templates/picture/edit.html.twig
  templates/picture/new.html.twig
  webpack.config.js
Labels: Changes done

#51 S 06 fix gallery on exposition
  assets/app.js
  assets/navbar.js
  composer.json
  composer.lock
  config/bundles.php
  src/Components/ExhibitionComponent.php
  src/Controller/PictureController.php
  src/Entity/Exhibition.php
  src/Entity/Picture.php
  src/Form/NewsletterType.php
  src/Form/PictureType.php
  src/Repository/ExhibitionRepository.php
  src/Repository/PictureRepository.php
  src/Service/CategoryService.php
  symfony.lock
  templates/base.html.twig
  templates/components/ExhibitionComponent.html.twig
  templates/includes/_navbar.html.twig
  templates/picture/edit.html.twig
  templates/picture/new.html.twig
  webpack.config.js
Labels: Changes done

#52 stat page with good route for gallery and show directly charts on click
  migrations/Version20230712121335.php
  src/Controller/AdminController.php
  src/Controller/PictureController.php
Labels: Changes requested

#56 S06 02 message toast
  assets/app.js
  assets/newsletter.js
  src/Form/NewsletterType.php
  templates/home/index.html.twig
  templates/home/newsletter_form.html.twig
  templates/includes/_sidebar.html.twig
  templates/includes/footer.html.twig
  webpack.config.js
Labels: Needs pair review

#59 S 06 Fix Stat and Twitter Callback / Add Style On NavBar
  assets/navbar.js
  src/Controller/TwitterController.php
  src/Service/StatisticService.php
  templates/picture/show.html.twig
Labels: Needs pair review

#60 S06 04 carousel path
  templates/home/index.html.twig
Labels: Needs pair review
